import { Property, Testimonial } from "@/types/property";

export const PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Modern Luxury Villa',
    description: 'Experience the ultimate luxury in this stunning modern villa with panoramic ocean views.',
    price: 2500000,
    location: 'Malibu, CA',
    beds: 5,
    baths: 6,
    sqft: 4500,
    type: 'Villa',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=2071&auto=format&fit=crop',
    featured: true,
  },
  {
    id: '2',
    title: 'Contemporary Downtown Apartment',
    description: 'High-rise living at its finest with floor-to-ceiling windows and premium amenities.',
    price: 850000,
    location: 'New York, NY',
    beds: 2,
    baths: 2,
    sqft: 1200,
    type: 'Apartment',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=2070&auto=format&fit=crop',
    featured: true,
  },
  {
    id: '3',
    title: 'Serene Mountain Retreat',
    description: 'A cozy cabin tucked away in the woods, perfect for a peaceful getaway.',
    price: 650000,
    location: 'Aspen, CO',
    beds: 3,
    baths: 2,
    sqft: 1800,
    type: 'House',
    image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1965&auto=format&fit=crop',
    featured: true,
  },
  {
    id: '4',
    title: 'Urban Chic Condo',
    description: 'Sleek design meets urban convenience in this centrally located condo.',
    price: 550000,
    location: 'Chicago, IL',
    beds: 1,
    baths: 1,
    sqft: 850,
    type: 'Condo',
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: '5',
    title: 'Mediterranean Style Estate',
    description: 'Classic architecture with modern luxury features and lush landscaping.',
    price: 3200000,
    location: 'Miami, FL',
    beds: 6,
    baths: 5,
    sqft: 5200,
    type: 'House',
    image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: '6',
    title: 'Beachfront Penthouse',
    description: 'Stunning penthouse with private elevator access and a massive rooftop terrace.',
    price: 4500000,
    location: 'Santa Monica, CA',
    beds: 4,
    baths: 4,
    sqft: 3800,
    type: 'Apartment',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop',
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    role: 'Homeowner',
    content: 'The team helped me find my dream home in record time. Their attention to detail and market knowledge is unmatched.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1974&auto=format&fit=crop',
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'Real Estate Investor',
    content: 'Professional, responsive, and data-driven. They are my go-to partners for all my property investments.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: '3',
    name: 'Emily Davis',
    role: 'First-time Buyer',
    content: 'Navigating the housing market was scary, but they made it so easy. I highly recommend their services!',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=2070&auto=format&fit=crop',
  }
];
